# General Settings
title = "Web_Dev - Clean & Minimal Portfolio Hugo Theme"
baseURL = "https://example.com/" # Replace with your site URL
languageCode = "en-us"
theme = "Web_Dev"
resourceDir = "resources"
paginate = 5
summaryLength = 50
DefaultContentLanguage = "en"

# Menu Settings
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "#home"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "#about"
    weight = 2

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "#services"
    weight = 3

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "#portfolio"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "#blog"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "#contact"
    weight = 6

# Main Settings
[params]
defaultLogo = "images/logo-dark.png"
defaultKeywords = ["clean", "minimal", "blog", "responsive", "google analytics", "bootstrap", "portfolio", "personal", "modern", "parallax", "hugo theme", "creative"]
defaultDescription = "Creative Designs - Clean & Minimal Portfolio Hugo Theme"
dateFormat = "January 2, 2006"
authorName = "Kevin Chisholm"
disqusComments = "" # YOUR DISQUS COMMENTS SHORTNAME
formspreeFormID = "" # YOUR FORMSPREE FORM ID
reCAPTCHAKey = "" # YOUR reCAPTCHA v2 key
googleMapsApiKey = "" # YOUR GOOGLE API KEY

[params.about]

[params.subscribe]

# Portfolio Settings (Filter)
[params.portfolio]

# Footer Settings
[params.footer]

# Social Settings
  [[params.social]]

# Sitemap Settings
[sitemap]

# Output Formats
[outputs]
home = ["HTML", "RSS", "JSON"]
