# General Settings
title = "Web_Dev - Clean & Minimal Portfolio Hugo Theme"
baseURL = "" #YOUR SITE URL
languageCode = "en-us"
theme = "Web_Dev"
resourceDir = "resources"
paginate = 5
summaryLength = 50
DefaultContentLanguage = "en" # Site language. Available translations in the theme's `/i18n` directory.


# Menu Settings
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = ""
  weight = 1
  
[[menu.main]]
  identifier = "pages"
  name = "Pages"
  url = ""
  weight = 2
  
[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  url = ""
  weight = 3
  
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = ""
  weight = 4
    
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = ""
  weight = 5
    

# Main Settings
[params]
defaultLogo = "Creative Designs"
defaultKeywords = ["clean", "minimal", "blog", "responsive", "google analytics", "bootstrap", "portfolio", "personal", "modern", "parallax", "hugo theme", "creative"]
defaultDescription = "Creative Designs - Clean & Minimal Portfolio Hugo Theme"
dateFormat = "January 2, 2006"
authorName = "Kevin Chisholm"
disqusComments = "" #YOUR DISQUS COMMENTS SHORTNAME
formspreeFormID = "" #YOUR FORMSPREE FORM ID
reCAPTCHAKey = "" #YOUR reCAPTCHA v2 key
googleMapsApiKey = "" #YOUR GOOGLE API KEY

# Sidebar Settings
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ] For General page "Blog"
position = "right" #SIDEBAR POSITION: [ left, right ] For General page "Blog"
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

[params.about]
about = 1 #SIDEBAR ABOUT WIDGET: [ 1 - yes, 0 - no ]
image = "images/author-blog.jpg"
name = "John Smith"
text = "<p>Can't multiply. Set set created thing light blessed third without. Him can't kind called set is second thing from you'll tree. Seed darkness you. Itself night. Life. Hath creature good.</p>"
[[params.about.social]]
icon = "fa-brands fa-x-twitter"
url = "https://www.twitter.com/"
[[params.about.social]]
icon = "fa-brands fa-facebook"
url = "https://facebook.com/"
[[params.about.social]]
icon = "fa-brands fa-dribbble"
url = "https://dribbble.com/"
[[params.about.social]]
icon = "fa-brands fa-youtube"
url = "https://www.youtube.com/"

[params.subscribe]
subscribe = 1 #SIDEBAR SUBSCRIBE WIDGET: [ 1 - yes, 0 - no ]
mailChimpURL = ""  # Example MailChimp url: http://xxx.xxx.list-manage.com/subscribe/post?u=xxx&id=xxx

# Portfolio Settings (Filter)
[params.portfolio]
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"
[[params.portfolio.filters]]
name = "Design"
slug = "design"
[[params.portfolio.filters]]
name = "Illustration"
slug = "illustration"

# Footer Settings
[params.footer]
copyright = "Creative Designs © 2025. Design & Coded by <a href='http://YourWebsite.com' target='_blank'> Creatives.</a>"

# Social Settings
[[params.social]]
title = "Twitter"
url = "https://www.twitter.com/"
[[params.social]]
title = "Facebook"
url = "https://facebook.com/"
[[params.social]]
title = "YouTube"
url = "https://www.youtube.com/"
[[params.social]]
title = "Dribbble"
url = "https://www.dribbble.com/"
[[params.social]]
title = "Instagram"
url = "https://www.instagram.com/"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]